server:
  port: 9080
  tomcat:
    max-connections: 1000
    max-threads: 500
    min-spare-threads: 10
  servlet:
      encoding:
        charset: UTF-8
        enabled: true

spring:
  profiles:
    active: local
    
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      # create create-drop update validate none
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  servlet:
    multipart:
      maxFileSize: 50000MB
      maxRequestSize: 5000MB
      
jwt:
  header: Authorization
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  token-validity-in-seconds: 86400