package kr.or.uknowhat.api.ubusiness.common;

public enum MessageType {
	JOIN, UNJOIN
	, CHAT
	, START, READPROB
	, WAITING, LOADING
	, ANSWER
	, OXP, OBP
	, TIMER, TIMEROFF, TIMECNT, TIMEOUT
	, CORRECT, INCORRECT
	, ANSCHK, ANSCHART, ANSUSERLIST
	, RANK, FINALRANK
	, EXIT
}
